Add whitelist and blacklist restrictions on attacking entity types
maruohon/tweakeroo pull request #318
Opened 2022-01-07 13:52 UTC by drunderscore

Similar to the Block Type Restriction, this Entity Type Restriction will prevent attacking entities if they are on the blacklist/not on the
whitelist.

This also introduces a helper restriction class, `EntityRestriction`.

2022-01-07 23:37 UTC, maruohon requested changes
Thanks. I left a couple of small code style notes, and one actual code change request.

2022-01-07 23:37 UTC, maruohon commented on src/main/java/fi/dy/masa/tweakeroo/tweaks/MiscTweaks.java
> +        if(MiscTweaks.ENTITY_TYPE_ATTACK_RESTRICTION.isAllowed(type) == false)
I always use a space in the if/for/while before the opening parenthesis. (Same thing in the Mixin.)

2022-01-07 23:37 UTC, maruohon commented on src/main/java/fi/dy/masa/tweakeroo/util/EntityRestriction.java
> +        for (var name : names)
I think I would write this as:
```java
            for (String name : names)
            {
                try
                {
                    Optional<EntityType<?>> type = Registry.ENTITY_TYPE.getOrEmpty(new Identifier(name));

                    if (type.isPresent())
                    {
                        set.add(type.get());
                        continue;
                    }
                }
                catch (Exception ignore) {}

                Tweakeroo.logger.warn("Invalid entity name in a black- or whitelist: '{}'", name);
            }
```

(Style notes: I don't like `var` to "hide" the type, and I use curly braces even for single line blocks.)

2022-01-08 00:04 UTC, drunderscore commented
I've implemented all the suggested changes.
Apologies if the force-push isn't appreciated here, I'm used to doing it to keep merges clean of "fixup" type commits.

2022-01-08 00:31 UTC, maruohon approved these changes

2022-01-08 00:35 UTC, merged